name: PerlIO-eol
version: 0.06
abstract: PerlIO layer for normalizing line endings
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  perl: 5.7.3
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
