abstract: PerlIO layer for normalizing line endings
author: Audrey Tang <audreyt@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: PerlIO-eol
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.7.3
version: 0.14
